[env:coreink]
platform = espressif32
board = m5stack-coreink
framework = arduino
monitor_speed = 115200
lib_deps =
    m5stack/M5GFX@^0.2.19
    m5stack/M5Core-Ink@^1.0.0
    bblanchon/ArduinoJson@^7.0.0
extra_scripts = pre:patch_gpio1.py
build_flags =
    -DCORE_DEBUG_LEVEL=3
